### ISSUE TITLE
Dialogue debugger does not work?

### ISSUE THREAD

**Issue by IAmNotIsaac** [Rubonnek/dialogue-engine#1]
This is coming from the demo. Seems like it doesn't work? Godot 4.2.1
![image](https://github.com/Rubonnek/dialogue-engine/assets/60862333/aba4406d-85ad-4aaa-a652-1dcdaede0b9b)

I should also mention it threw me a warning when I opened it, stating it was last edited using 4.3 (currently not latest stable, that would be 4.2.1). As well, following error(s):
![image](https://github.com/Rubonnek/dialogue-engine/assets/60862333/88620a9d-526f-4761-bf80-50cce7e5e31d)

**Comment by Rubonnek** [comment]
Is the `Dialogue Engine Viewer` enabled?

Looks like you need to enable it through  `Project Settings -> Plugins -> Dialogue Engine Viewer`

**Comment by Rubonnek** [comment]
> I should also mention it threw me a warning when I opened it, stating it was last edited using 4.3 (currently not latest stable, that would be 4.2.1).

What platform are you using? I don't see this warning in Linux. I'm unable to reproduce, but I think I know where this issue is coming from.

**Comment by IAmNotIsaac** [comment]
It's odd, I don't recall changing anything, but everything seems to be working flawlessly now? I no longer get any errors and the viewer works just fine now. I didn't even have to turn it on, it seemed already to be. Must be some odd one-off thing.

For reference though, my system info:
Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.14072.2) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads)

**Comment by Rubonnek** [comment]
> It's odd, I don't recall changing anything, but everything seems to be working flawlessly now? I no longer get any errors and the viewer works just fine now. I didn't even have to turn it on, it seemed already to be. Must be some odd one-off thing.

When opening/downloading a new project or addon, sometimes it's important to close and reopen Godot after it's import process finishes. Internally Godot stores a list of files that need to be processed the next time Godot opens to resolve some of their dependencies properly. I assume that's what happened here.

> For reference though, my system info:
> Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.14072.2) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads)

Thanks. This helps.
