### ISSUE TITLE
Installing addon puts .github/FUNDING.yml in project

### ISSUE THREAD

**Issue by ameoverflow** [Rubonnek/dialogue-engine#5]
Installing addon adds a FUNDING.yml file to project root, which GitHub displays as a donation widget. I'm not sure if that's the intended behavior.

**Comment by Rubonnek** [comment]
Not intended. I believe there's a way to avoid certain files on a release archive. I'll look into it.

**Comment by Rubonnek** [comment]
Thanks for opening the issue. I've stumbled upon a release workflow I like. Releases will no longer include .github/FUNDING.yml. I've also removed other unnecessary files from the exported archive.
